name: CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup
      run: |
        mkdir build
    - name: Clone zserio
      run: |
        git clone --recurse-submodules -b v2.4.0-pre2 https://github.com/ndsev/zserio.git zserio
    - name: Configure
      working-directory: build
      run: >
        cmake
        -DCMAKE_BUILD_TYPE=Debug
        -DZSERIO_RT_DIR=../zserio/compiler/extensions/cpp/runtime/src
        ..
    - name: Build runtime
      working-directory: build
      run: |
        cmake --build .
    - name: Run CTest
      working-directory: build/runtime
      run: |
        ctest --verbose --no-tests=error

  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup
      run: |
        mkdir build
    - name: Clone zserio
      run: |
        git clone --recurse-submodules -b v2.4.0-pre2 https://github.com/ndsev/zserio.git zserio
    - name: Configure
      working-directory: build
      run: >
        cmake
        -DCMAKE_BUILD_TYPE=Debug
        -DZSERIO_RT_DIR=../zserio/compiler/extensions/cpp/runtime/src
        ..
      shell: cmd
    - name: Build runtime
      working-directory: build
      run: |
        cmake --build .
      shell: cmd
    - name: Run CTest
      working-directory: build/runtime
      run: |
        ctest -C Debug --verbose --no-tests=error
      shell: cmd

  build-macos:
    name: MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup
      run: |
        mkdir build
        brew install ant
    - name: Clone zserio
      run: |
        git clone --recurse-submodules -b v2.4.0-pre2 https://github.com/ndsev/zserio.git zserio
    - name: Configure
      working-directory: build
      run: >
        cmake
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_CXX_STANDARD=17
        -DZSERIO_RT_DIR=../zserio/compiler/extensions/cpp/runtime/src
        ..
    - name: Build runtime
      working-directory: build
      run: |
        cmake --build .
    - name: Run CTest
      working-directory: build/runtime
      run: |
        ctest -C Debug --verbose --no-tests=error
